runtime: go115

instance_class: F1

automatic_scaling:
    max_instances: 1

handlers:
    - url: /public
      static_dir: public

    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto
